env:
  es2021: true
  node: true
extends:
  - "airbnb-base"
  - "plugin:json/recommended"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  linebreak-style: off
  comma-dangle:
    - error
    - never
  no-console: off
